import { InfoCircledIcon } from "@radix-ui/react-icons";
import { Badge, Box, Callout, Flex, Link, Text } from "@radix-ui/themes";
import { useEffect, useState } from "react";
import ImageCarousel from "./ImageCarousel";
import StarRating from "./StarRating";
import type { Result } from "./hooks/types";
import useReportFilter from "./hooks/useReportFilter";

const Current = () => {
  const { resultMatchingURL } = useReportFilter();

  const [currentResult, setCurrentResult] = useState<Result>();

  useEffect(() => {
    if (resultMatchingURL != undefined) {
      setCurrentResult(resultMatchingURL);
      document.body.scrollTo({
        top: 0,
        behavior: "smooth",
      });
    }
  }, [resultMatchingURL]);

  useEffect(() => {
    console.log(currentResult);
  }, [currentResult]);
  return (
    currentResult && (
      <Box className="w-full mb-10">
        <Flex
          direction="column"
          className="gap-6 md:p-8 p-4 rounded-xl shadow-lg max-w-screen-lg mx-auto"
        >
          <StarRating alignment={currentResult.alignment} />

          <Text size="6" weight="bold" className="leading-tight max-w-[600px]">
            {currentResult.title}
          </Text>

          <Text size="3" className="leading-relaxed tracking-wide">
            {currentResult.summary}
          </Text>

          <Callout.Root>
            <Callout.Icon>
              <InfoCircledIcon />
            </Callout.Icon>
            <Callout.Text>
              The above summary and meta information were generated by AI. Please verify the
              information with the original source by reading the full report.
            </Callout.Text>
          </Callout.Root>

          <Flex gap="3" wrap="wrap" className="pt-2">
            {currentResult.tags?.map(tag => (
              <Text
                size="1"
                key={tag}
                className="text-blue-400 bg-blue-950/20 px-2 py-1 rounded-full"
              >
                #{tag}
              </Text>
            ))}
          </Flex>

          {/* Biases */}
          <Flex gap="1" wrap="wrap" mt="2" className="min-h-[1rem]">
            {currentResult.politicalBiases?.length > 0 &&
              currentResult.politicalBiases.map(bias => (
                <Badge size="1" color="blue" key={bias}>
                  {bias}
                </Badge>
              ))}
          </Flex>

          <Box className="pt-4">
            <Link href={currentResult.href} className="text-base font-medium">
              Read full report →
            </Link>
          </Box>

          {/* Image */}
          <Box
            className={`${!currentResult.images?.length && "bg-gray-300 animate-pulse"} !flex gap-2 overflow-hidden !min-w-[120px] !min-h-[120px] rounded-md border-2 p-2 border-gray-700`}
          >
            {currentResult.images?.length ? <ImageCarousel images={currentResult.images} /> : <></>}
          </Box>
        </Flex>
      </Box>
    )
  );
};

export default Current;
